name: Docker Image Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . -t fabiocrestani/house-docker-image
    - name: Deploy the Docker image into DockerHub
      run: docker push fabiocrestani/house-docker-image
